spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

app-config:
  cache:
    ttl: 120
    scheduler: 0 * * * * *
    redis-enabled: true
  client:
    viacep: https://viacep.com.br/ws/%s/json